config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vetešnictví Depot</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store" >
  <div id="banner" >
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatická knihovna" %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
          <% end %>
      <% end %>
  <ul>
      <li><a href="/">Úvod</a></li>
      <li><a href="/faq">FAQ</a></li>
      <li><a href="/news">Novinky</a></li>
      <li><a href="/contact">Kontaktní údaje</a></li>
  </ul>

  <% if session[:user_id] %>
  <ul>
  <li><%= link_to 'Objednávky', orders_path %></li>
  <li><%= link_to 'Produkty', products_path %></li>
  <li><%= link_to 'Uživatelé', users_path %></li>
  </ul>
  <%= button_to 'Odhlášení', logout_path, method: :delete %>
  <% end %>
</div>
<div id="main" >
  <%= yield %>
</div>
</div>

</body>
</html>